[build]
  command = "npm run build"
  publish = "public"

# Serve static files only
[[redirects]]
  from = "/articles/:slug"
  to = "/articles/:slug.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200